#!/bin/bash
#Author: Paulo Jerônimo (@paulojeronimo, pj@paulojeronimo.info)
#
# Esse script deve ser executado como root, 
# após a realização da instalação mínima do Fedora 

export PJ_UID=501
export STAFF_GID=20

sed -i '
  s/^\(%wheel.*ALL\)/#\1/
  s/^#\(%wheel.*NOPASSWD.*\)/\1/
' /etc/sudoers

for f in fedora.repo fedora-updates.repo
do
  baseurl='file:///data/mirrors/Fedora-$releasever-$basearch'
  case $f in
    fedora.repo) baseurl=$baseurl'/releases/$releasever/Everything/$basearch/os/';;
    fedora-updates.repo) baseurl=$baseurl'/updates/$releasever/$basearch/';;
  esac
  sed -i "
    1,/^#baseurl=/{ s,^#\(baseurl=\).*$,\1$baseurl, ; }
    1,/^metalink=/{ s,^\(metalink=.*\)$,#\1, ; }
  " /etc/yum.repos.d/$f
done

groupmod -g 200 games
groupadd -g $STAFF_GID staff
useradd -m -s /bin/bash -G wheel -u $PJ_UID -g staff pj
passwd pj

#echo "/dev/sda4	/data hfsplus defaults 0 0" >> /etc/fstab
#mount /data

mount /dev/sdc2 /mnt

mirrors=/data/mirrors
rm -f $mirrors
mkdir -p $mirrors
ln -s /mnt/mirrors/Fedora-20-x86_64 $mirrors

yum -y update
shutdown -r now
