#!/bin/bash
# Author: Paulo Jeronimo (@paulojeronimo, paulojeronimo@gmail.com)
#
# Este script deve ser executado como root

MY_USER=${MY_USER:-pj}
MY_GROUP=${MY_GROUP:-staff}
PASSWD=senhapadrao

export MY_UID=501
export MY_GID=20

sed -i '
  s/^\(%wheel.*ALL\)/#\1/
  s/^# \(%wheel.*NOPASSWD.*\)/\1/
' /etc/sudoers

cat > /etc/yum.repos.d/local-mirror.repo <<'EOF'
[local-mirror-fedora]
name=Local fedora $releasever - $basearch
failovermethod=priority
baseurl=file:///data/mirrors/Fedora-$releasever-$basearch/releases/$releasever/Everything/$basearch/os/
enabled=1
metadata_expire=7d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-20-$basearch
proxy=_none_

[local-mirror-updates]
name=Local fedora $releasever - $basearch - Updates
failovermethod=priority
baseurl=file:///data/mirrors/Fedora-$releasever-$basearch/updates/$releasever/$basearch/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-20-$basearch
proxy=_none_
EOF

for f in fedora.repo updates.repo
do
  sed -i '
    s/^\(enable=\)0/\11/
  ' /etc/yum.repos.d/$f
done

ln -s /mnt /"HD Externo"
#mkdir -p /data/mirrors
#cd /data/mirrors
#l=Fedora-20-x86_64
#[ -L $l ] && rm -f $l
#ln -s /mnt/mirrors/$l

groupmod -g 200 games
groupadd -g $MY_GID $MY_GROUP
useradd -m -s /bin/bash -G wheel -u $MY_UID -g $MY_GROUP $MY_USER
echo $PASSWD | passwd $MY_USER --stdin

yum -y update
shutdown -r now

# vim: set ts=2 sw=2 expandtab:
