#!/bin/bash
# Author: Paulo Jeronimo (@paulojeronimo, paulojeronimo@gmail.com)
#
# Este script deve ser executado com o usuário $MY_USER (criado em do1)

sudo yum -y group install \
development-tools \
gnome-desktop-environment

sudo yum -y install \
yum-utils \
vim-enhanced \
lynx \
tmux \
tree

sudo package-cleanup -y --oldkernels --count=1

sudo ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target

sudo init 5

# vim: set ts=2 sw=2 expandtab:
