#!/bin/bash
# Author: Paulo Jeronimo (@paulojeronimo, paulojeronimo@gmail.com)
#
# Este script deve ser executado como $MY_USER e dentro de uma sessão GNOME

MY_USER=${MY_USER:-pj}
CONFIG_HOME=${CONFIG_HOME:-/data/$MY_USER/Projects/github.com/paulojeronimo/dotfiles/.scripts/criar-links-data}

# configura o diretório home criando links para os arquivos em /data/$MY_USER
[ -x "$CONFIG_HOME" ] && $CONFIG_HOME

# instala o Fedy e, a partir dele, outros softwares
curl -sSL https://satya164.github.io/fedy/fedy-installer | sudo bash
sudo fedy -e \
  adobe_flash\
  core_fonts\
  dvd_playback\
  font_rendering\
  google_chrome\
  google_talkplugin\
  media_codecs\
  nautilus_dropbox\
  oracle_jdk\
  skype_linux\
  teamviewer_linux

# instala outros softwares
sudo yum -y install \
  vlc

# ajusta o C cedilha
sudo yum -y install gtk3-immodules.x86_64
sudo sed -i 's/^\("cedilla".*:co\)\(.*\)/\1:en_US\2/g' /usr/lib64/gtk-3.0/3.0.0/immodules.cache
gsettings set org.gnome.settings-daemon.plugins.keyboard active false
imsettings-switch im-cedilla

# encerra a sessão GNOME
gnome-session-quit --no-prompt

# vim: set ts=2 sw=2 expandtab:
